spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/management
    username: ankhangnumber1
    password: ankhangnumber1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect